/**
    Abilities Module -  Parsers
    Additional run time parsers of special types
**/

module.exports = function() {
    
    /**
    Parse Selector
    parses a selector / target type
    and returns a list of discord player ids
    **/
    this.parsePlayerSelector = function(selector, self) {
        let selectorTarget = selectorGetTarget(selector);
        let selectorType = selectorGetType(selector);
        switch(selectorType) {
            case "player": 
                return parsePlayerSelector(selector, self);
            default:
                abilityLog(`❗ **Error:** Invalid selector type \`${selectorType}\`!`);
                return [];
        }
    }
    
    /**
    Parse Player Selector
    parses a selector / target type
    and returns a list of discord player ids
    **/
    const ID_SELECTOR = /^@id:(\d+)$/;
    this.parsePlayerSelector = function(selector, self) {
        let selectorTarget = selectorGetTarget(selector);
        /** WIP: Needs to be able to parse much more! **/
        switch(selectorTarget) {
            // base selectors
            case "@self":
            return [ self ];
            // unknown selector
            default:
                if(ID_SELECTOR.test(selectorTarget)) { // id selector - this is not in formalizations; this is generated by prompt replies
                    let id = selectorTarget.match(ID_SELECTOR)[1];
                    return [ id ];
                } else {
                    abilityLog(`❗ **Error:** Invalid player selector target \`${selectorTarget}\`!`);
                    return [ ];
                }
        }
    }
    
    /**
    Get Selector Target
    returns the target of a selector (removing the type)
    **/
    this.selectorGetTarget = function(selector) {
        return selector.split("[")[0].toLowerCase();
    }
    
    /**
    Get Selector Type
    returns the type of a selector (removing the target)
    **/
    this.selectorGetType = function(selector) {
        return selector.split("[")[1].split("]")[0].toLowerCase();
    }
    
    /**
    Parse Group Name
    parses a group name
    **/
    this.parseGroupName = function(name) {
        return name.replace("#", "").replace(/\-/g, " ").toLowerCase();
    }
    
    /**
    Parse Duration
    parses a duration type, WIP: I suppose this should verify its a valid duration type!!
    **/
    this.parseDuration = function(dur) {
        return dur.toLowerCase();
    }
    
}